--- Deterministic corpus generator for the perf harness.
---
--- Run directly (`nvim -u NONE -l perf/corpus/gen_corpus.lua`) or let a
--- benchmark script call it through `lib/bench.lua:corpus()`. The generated
--- files are intentionally NOT committed: they are large and reproducible.

local uv = vim.uv

local dir = vim.fs.dirname(debug.getinfo(1, 'S').source:sub(2))

-- Deterministic PRNG (LCG), so every machine and every wave sees byte-identical
-- corpora regardless of the Lua version's math.random.
local seed = 0x2545F491
local function rnd(n)
  seed = (1103515245 * seed + 12345) % 2147483648
  -- Use the high bits: the low bits of an LCG have very short periods and
  -- would make the corpus visibly periodic.
  return (math.floor(seed / 65536) % n) + 1
end

local function pick(t)
  return t[rnd(#t)]
end

local function write(path, lines)
  local f = assert(io.open(path, 'w'))
  f:write(table.concat(lines, '\n'), '\n')
  f:close()
  local st = uv.fs_stat(path)
  io.stderr:write(string.format('  %s: %d lines, %d bytes\n', path, #lines, st and st.size or 0))
end

local types = { 'int', 'size_t', 'char *', 'const char *', 'uint32_t', 'bool', 'double', 'void *' }
local names =
  { 'buf', 'len', 'idx', 'count', 'ptr', 'row', 'col', 'attr', 'grid', 'cell', 'state', 'hl' }
local verbs =
  { 'update', 'flush', 'compute', 'reset', 'append', 'lookup', 'encode', 'decode', 'scan' }

--- Generate plausible C source of at least `n` lines.
--- @param n integer
--- @return string[]
local function c_source(n)
  local out = {
    '// Generated by perf/corpus/gen_corpus.lua -- do not edit, do not commit.',
    '#include <stdbool.h>',
    '#include <stddef.h>',
    '#include <stdint.h>',
    '#include <string.h>',
    '',
  }
  local i = 0
  while #out < n do
    i = i + 1
    local fname = string.format('%s_%s_%d', pick(verbs), pick(names), i)
    local rt = pick(types)
    out[#out + 1] =
      string.format('/// %s the %s buffer for row %d.', pick(verbs), pick(names), rnd(4096))
    out[#out + 1] = string.format(
      'static %s %s(%s %s, %s %s)',
      rt,
      fname,
      pick(types),
      pick(names),
      pick(types),
      pick(names)
    )
    out[#out + 1] = '{'
    local body = rnd(12) + 3
    for _ = 1, body do
      local k = rnd(6)
      if k == 1 then
        out[#out + 1] = string.format(
          '  %s %s_%d = (%s)%d;',
          pick(types),
          pick(names),
          rnd(999),
          pick(types),
          rnd(65536)
        )
      elseif k == 2 then
        out[#out + 1] =
          string.format('  if (%s > %d && %s != NULL) {', pick(names), rnd(256), pick(names))
        out[#out + 1] = string.format('    %s += %d;  // %s', pick(names), rnd(64), pick(verbs))
        out[#out + 1] = '  }'
      elseif k == 3 then
        out[#out + 1] = string.format('  for (size_t i = 0; i < %s; i++) {', pick(names))
        out[#out + 1] = string.format(
          '    %s[i] = (%s)(%s[i] ^ 0x%02x);',
          pick(names),
          pick(types),
          pick(names),
          rnd(255)
        )
        out[#out + 1] = '  }'
      elseif k == 4 then
        out[#out + 1] = string.format('  memcpy(%s, %s, %d);', pick(names), pick(names), rnd(4096))
      elseif k == 5 then
        out[#out + 1] = string.format('  switch (%s) {', pick(names))
        out[#out + 1] = string.format('  case %d:', rnd(32))
        out[#out + 1] = string.format('    %s = %d;', pick(names), rnd(1024))
        out[#out + 1] = '    break;'
        out[#out + 1] = '  default:'
        out[#out + 1] = '    break;'
        out[#out + 1] = '  }'
      else
        out[#out + 1] = string.format(
          '  const char *msg_%d = "%s %s: %d";',
          rnd(9999),
          pick(verbs),
          pick(names),
          rnd(9999)
        )
      end
    end
    if rt == 'bool' then
      out[#out + 1] = string.format('  return %s > %d;', pick(names), rnd(32))
    elseif rt == 'int' or rt == 'size_t' or rt == 'uint32_t' or rt == 'double' then
      out[#out + 1] = string.format('  return (%s)%d;', rt, rnd(4096))
    else
      out[#out + 1] = '  return NULL;'
    end
    out[#out + 1] = '}'
    out[#out + 1] = ''
  end
  return out
end

--- CJK/emoji/combining-heavy text: the width and multibyte hot paths.
--- @param n integer
--- @return string[]
local function cjk_text(n)
  local han = {}
  for cp = 0x4E00, 0x4E00 + 511 do
    han[#han + 1] = vim.fn.nr2char(cp)
  end
  local kana = {}
  for cp = 0x3041, 0x3096 do
    kana[#kana + 1] = vim.fn.nr2char(cp)
  end
  local hangul = {}
  for cp = 0xAC00, 0xAC00 + 255 do
    hangul[#hangul + 1] = vim.fn.nr2char(cp)
  end
  local emoji = {}
  for _, cp in ipairs({ 0x1F600, 0x1F602, 0x1F680, 0x1F604, 0x1F60E, 0x2764, 0x1F44D, 0x1F525 }) do
    emoji[#emoji + 1] = vim.fn.nr2char(cp)
  end
  -- Combining marks exercise the grapheme-cluster path (utfc_ptr2schar).
  local combining = { vim.fn.nr2char(0x0301), vim.fn.nr2char(0x0308), vim.fn.nr2char(0x0327) }
  local latin = { 'e', 'a', 'o', 'u', 'n', 'c' }

  local out = { '# Generated by perf/corpus/gen_corpus.lua -- do not edit, do not commit.' }
  while #out < n do
    local parts = {}
    local cells = 0
    while cells < 76 do
      local k = rnd(10)
      if k <= 4 then
        parts[#parts + 1] = pick(han)
        cells = cells + 2
      elseif k <= 6 then
        parts[#parts + 1] = pick(kana)
        cells = cells + 2
      elseif k == 7 then
        parts[#parts + 1] = pick(hangul)
        cells = cells + 2
      elseif k == 8 then
        parts[#parts + 1] = pick(emoji)
        cells = cells + 2
      elseif k == 9 then
        parts[#parts + 1] = pick(latin) .. pick(combining)
        cells = cells + 1
      else
        parts[#parts + 1] = ' ' .. tostring(rnd(9999)) .. ' '
        cells = cells + 6
      end
    end
    out[#out + 1] = table.concat(parts)
  end
  return out
end

write(dir .. '/ascii.c', c_source(6000))
write(dir .. '/cjk.txt', cjk_text(6000))
write(dir .. '/big.c', c_source(24000))
