get_externalproject_options(mimalloc ${DEPS_IGNORE_SHA})
ExternalProject_Add(mimalloc
  DOWNLOAD_DIR ${DEPS_DOWNLOAD_DIR}/mimalloc
  CMAKE_ARGS ${DEPS_CMAKE_ARGS}
    -Wno-dev
    -DCMAKE_BUILD_TYPE:STRING=Release
    -DMI_BUILD_OBJECT:BOOL=OFF
    -DMI_BUILD_SHARED:BOOL=OFF
    -DMI_BUILD_STATIC:BOOL=ON
    -DMI_BUILD_TESTS:BOOL=OFF
    -DMI_USE_CXX:BOOL=OFF
    -DMI_OVERRIDE:BOOL=OFF
    -DMI_SKIP_COLLECT_ON_EXIT:BOOL=ON
    -DCMAKE_INSTALL_PREFIX=${DEPS_INSTALL_DIR}
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_GENERATOR=${CMAKE_GENERATOR}
  ${EXTERNALPROJECT_OPTIONS}
  BUILD_COMMAND ${CMAKE_COMMAND} --build . --target all --config ${CMAKE_BUILD_TYPE}
  INSTALL_COMMAND ${CMAKE_COMMAND} --build . --target install --config ${CMAKE_BUILD_TYPE} &&
    mv ${DEPS_INSTALL_DIR}/include/mimalloc-2.1/ ${DEPS_INSTALL_DIR}/include/mimalloc &&
    mv ${DEPS_INSTALL_DIR}/lib/mimalloc-2.1/libmimalloc.a ${DEPS_INSTALL_DIR}/lib)
