get_externalproject_options(mimalloc ${DEPS_IGNORE_SHA})
ExternalProject_Add(mimalloc
  DOWNLOAD_DIR ${DEPS_DOWNLOAD_DIR}/mimalloc
  CMAKE_ARGS ${DEPS_CMAKE_ARGS}
    -D MI_BUILD_SHARED=OFF
    -D MI_BUILD_STATIC=ON
    -D MI_BUILD_OBJECT=OFF
    -D MI_BUILD_TESTS=OFF
    -D MI_INSTALL_TOPLEVEL=ON
    -D MI_OVERRIDE=ON
    -D MI_OSX_INTERPOSE=ON
    -D MI_OSX_ZONE=ON
    -D MI_OPT_ARCH=ON
    -D MI_OPT_SIMD=ON
  ${EXTERNALPROJECT_OPTIONS})
